config/routes.rb
Rails.application.routes.draw do
  # you can add a conditional to only show this route to admins
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  root "pages#home"
  get "home" => "pages#home"
  devise_for :users

  resources :matches do
    resources :messages
  end



  put "/matches/:username/like", to: "matches#like", as: "like_match_by_username"

  put "/matches/:username/reject", to: "matches#reject", as: "reject_match_by_username"

   get "users/:username/messages", to: "users#messages", as: :user_messages

   get "/:username", to: "users#show", as: :user

  resources :users do
    collection do
      get "discover", to: "users#index", as: :discover_users
    end
  end

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id          :bigint           not null, primary key
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  match_id    :bigint           not null
#  receiver_id :bigint           not null
#  sender_id   :bigint           not null
#
# Indexes
#
#  index_messages_on_match_id     (match_id)
#  index_messages_on_receiver_id  (receiver_id)
#  index_messages_on_sender_id    (sender_id)
#
# Foreign Keys
#
#  fk_rails_...  (match_id => matches.id)
#  fk_rails_...  (receiver_id => users.id)
#  fk_rails_...  (sender_id => users.id)
#
class Message < ApplicationRecord
  belongs_to :match
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  validates :body, presence: true
  
  scope :for_match, ->(match_id) { where(match_id: match_id) }
  scope :from_user, ->(user_id) { where(sender_id: user_id) }
  scope :to_user, ->(user_id) { where(receiver_id: user_id) }


  def self.for_user_in_accepted_matches(user_id)
    joins(:match)
      .where(matches: { status: "accepted" })
      .where("messages.sender_id = ? OR messages.receiver_id = ?", user_id, user_id)
  end

  def self.accepted_between(user1_id, user2_id)
    joins(:match)
      .where(matches: { status: "accepted" })
      .where("(messages.sender_id = :user1_id AND messages.receiver_id = :user2_id) OR (messages.sender_id = :user2_id AND messages.receiver_id = :user1_id)", user1_id: user1_id, user2_id: user2_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]
  before_action :set_match, only: %i[create]
  before_action { authorize (@message || Message) }

  # GET /messages or /messages.json


  def index
    @match = Match.find(params[:match_id])
    @new_message = Message.new
  
    if params[:last_message_id]
   
      @messages = @match.messages.where("id < ?", params[:last_message_id]).order(created_at: :asc).limit(20)
    else
    
      @messages = @match.messages.order(created_at: :desc).limit(20)
    end

    respond_to do |format|
      format.html { render :index }
      format.js
    end
  end  
  


  # GET /messages/1 or /messages/1.json
  def show
    @match = Match.find(params[:match_id])
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @match = Match.find(params[:match_id])
    @message = @match.messages.build(message_params)
    @message.sender_id = current_user.id

    # Determine the receiver as the other user in the match
    @message.receiver_id = if @match.requester_id == current_user.id
        @match.approver_id
      else
        @match.requester_id
      end

    if @message.sender_id == @message.receiver_id
      redirect_to matches_path, alert: "Cannot send messages to yourself."
      return
    end

    if @match.status != "accepted" || (@match.requester_id != current_user.id && @match.approver_id != current_user.id)
      redirect_to matches_path, alert: "Not authorized to send messages."
      return
    end

    respond_to do |format|
      if @message.save
        format.html { redirect_to match_messages_path(@match, :anchor => "wall"), notice: "Message was successfully sent." }
        format.json { render :show, status: :created, location: @message }
        # ActionCable.server.broadcast "match_#{@message.match_id}", message: render_message(message)
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  def set_match
    @match = Match.find(params[:match_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to(root_path, alert: "Match not found.")
  end

  # Only allow a list of trusted parameters through.

  def message_params
    params.require(:message).permit(:body, :receiver_id)
  end

  #   def render_message(message)
  #   ApplicationController.renderer.render(partial: 'messages/message', locals: { message: @message })
  # end

end

app/views/messages/_form.html.erb
<%= form_with(model: [ @match, Message.new ], local: false, html: { id: "new_message_form", class: "message-form" }) do |form| %>
  <% if @message && @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
        <% @message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :body, required: true, placeholder: "Type a message..." %>
  </div>

  <%= form.submit "Send" %>
<% end %>

app/views/messages/_message.html.erb
<li>
  <div class="row">
    <% if message.sender_id == current_user.id %>
      <div class="message-sent">
        <%= message.body %>
      </div>
    <% else %>
      <div class="message-received">
        <%= message.body %>
      </div>
    <% end %>
  </div>
</li>

app/views/messages/create.js.erb
<% if @message.persisted? %>
  console.log("Adding new message to the DOM");
  var newMessage = $("<%= j(render @message) %>");
  $("#messages").append(newMessage);

  newMessage.slideDown(function() {
    var messagesContainer = $("#messages");
    messagesContainer.scrollTop(messagesContainer.prop("scrollHeight"));
  });

  $("#new_message_form textarea").val(""); // Clear the text area after message is added
<% else %>
  console.log("Message not sent");
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", match_message_path %>
</div>

app/views/messages/index.html.erb
<div class="container">
  <div class="list-group">
    <% @messages.reverse.each do |message| %>
      <% if message.sender == current_user %>
        <div class="list-group-item list-group-item-action d-flex flex-column align-items-end message-bubble sent-by-user">
          <p class="mb-0">
            <%= message.body %>
          </p>
          <small class="timestamp">
            <%= message.created_at.strftime("%b %d, %Y %H:%M") %>
          </small>
        </div>
      <% else %>
        <div class="list-group-item list-group-item-action d-flex flex-column align-items-start message-bubble received-message">
          <b><%= message.sender.username %></b>
          <% if message.sender.avatar.attached? %>
            <%= image_tag(message.sender.avatar, size: "30x30", class: "rounded-circle flex-shrink-0", alt: "#{message.sender.full_name.titleize}'s avatar") %>
            
          <% end %>
          <p class="mb-0">
            <%= message.body %>
          </p>
          <small class="timestamp">
            <%= message.created_at.strftime("%b %d, %Y %H:%M") %>
          </small>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= render "form", message: Message.new %>

app/views/messages/index.js.erb
document.addEventListener("DOMContentLoaded", function() {
  var messageList = document.querySelector(".list-group");

  // Ensure that there"s actually a message list on the page to attach the event
  if (messageList) {
    messageList.addEventListener("scroll", function() {
      if (messageList.scrollTop === 0) {
        var firstMessageId = document.querySelector(".list-group-item").getAttribute("data-message-id");
        // Ensure matchId is dynamically retrieved or correctly set
        var matchId = window.location.pathname.split("/")[2]; // Assuming URL pattern /matches/:match_id/messages

        fetch(`/matches/${matchId}/messages?last_message_id=${firstMessageId}`, {
          credentials: "include" // Ensure cookies/session are included if needed for authentication
        })
          .then(response => response.text())
          .then(function(html) {
            // Prepend fetched messages to the list
            messageList.innerHTML = html + messageList.innerHTML;
          })
          .catch(error => console.error("Failed to load messages:", error));
      }
    });
  } else {
    console.log("Message list element not found.");
  }
});

<!---->

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", match_messages_path(@match) %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", match_message_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>