config/routes.rb
Rails.application.routes.draw do
  # you can add a conditional to only show this route to admins
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  root "pages#home"
  get "home" => "pages#home"
  devise_for :users

  resources :matches do
    resources :messages
  end



  put "/matches/:username/like", to: "matches#like", as: "like_match_by_username"

  put "/matches/:username/reject", to: "matches#reject", as: "reject_match_by_username"

   get "users/:username/messages", to: "users#messages", as: :user_messages

   get "/:username", to: "users#show", as: :user

  resources :users do
    collection do
      get "discover", to: "users#index", as: :discover_users
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean          default(FALSE), not null
#  bio                    :text
#  dob                    :date
#  email                  :citext           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  gender                 :string
#  gym_frequency_category :string
#  ideal_match_gender     :string           default([]), is an Array
#  last_name              :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  skill_level            :string
#  time_of_day            :string
#  type_of_workouts       :string
#  user_gym               :string
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#
class User < ApplicationRecord
  include FileSizeValidator
  include UserEnumsAndScopes
  include UserRelationships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :dob, presence: true
  validates :username, presence: true

  
  def gym_name
    {
      east_bank_club: "East Bank Club",
      esporta_fitness: "Esporta Fitness",
      equinox: "Equinox",
      la_fitness: "LA Fitness",
      planet_fitness: "Planet Fitness",
      fitness_formula_club: "Fitness Formula Club",
      midtown_athletic_club: "Midtown Athletic Club",
      orange_theory_fitness: "Orange Theory Fitness",
    }[self.user_gym.to_sym] || self.user_gym
  end

  def self.gym_name_options
    user_gyms.keys.map do |key|
      [User.new(user_gym: key).gym_name, key]
    end
  end

  def user_gym_frequency
    {
      daily: "daily",
      twice_a_week: "twice a week",
      multiple_times_a_week: "multiple times a week",
      weekly: "weekly",
      every_two_weeks: "every two weeks",
      occasionally: "occasionally",
      rarely: "rarely",
    }[self.gym_frequency_category] || self.gym_frequency_category
  end

  def self.user_gym_frequency_options
    gym_frequency_categories.keys.map do |key|
      [User.new(gym_frequency_category: key).user_gym_frequency, key]
    end
  end

  def workouts
    {
      cardio: "cardio",
      strength_training: "strength training",
      hiit: "hiit",
      crossfit: "crossfit",
      yoga: "yoga",
      pilates: "pilates",
      dance: "dance",
      martial_arts: "martial arts",
      spinning: "spinning",
      bodybuilding: "bodybuilding",
      mixed_modal: "mixed modal",
    }[self.type_of_workouts] || self.type_of_workouts
  end

  def self.workouts_options
    gym_frequency_categories.keys.map do |key|
      [User.new(gym_frequency_category: key).user_gym_frequency, key]
    end
  end

  def age
    return unless dob

    now = Time.zone.now.to_date
    age = now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
    age
  end

  def full_name
    [first_name, last_name].join(" ")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:messages]
  before_action :authorize_user, only: [:messages]
  before_action { authorize @user || User }
  
  def show
    @user = User.find_by!(username: params.fetch(:username))
  end
  
  def edit
  end

  def index
    accepted_matches_user_ids = Match.where(status: "accepted").where("requester_id = ? OR approver_id = ?", current_user.id, current_user.id).pluck(:requester_id, :approver_id).flatten.uniq
  
    @users = User.where.not(id: [current_user.id, *accepted_matches_user_ids])
  end

  def messages
    @user = current_user
    
    matches = Match.where(status: "accepted").where("requester_id = :user_id OR approver_id = :user_id", user_id: @user.id)
    
    @messages = matches.map do |match|
      match.messages.order(updated_at: :desc).first
    end.compact 
  end
  
  
  

  private


  # these represent all the fields that will be saved when a user creates an account
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :first_name, :last_name, :bio, :dob, :gender, :user_gym_frequency, :workouts, :avatar, :time_of_day, :skill_level, :additional_files, :additional_files_2, :additional_files_3, ideal_match_genders: [])
  end

  def set_user
    if params[:username]
      @user = User.find_by!(username: params.fetch(:username))
    else
      @user = current_user
    end
  end

  def authorize_user
    unless current_user == @user
      redirect_to root_path, alert: "You are not authorized to view these messages."
    end
  end
end

app/views/users/index.html.erb
<div id="usersCarousel" class="carousel slide">
  <div class="carousel-inner">
    <% @users.each_with_index do |user, index| %>
      <div class="carousel-item <%= "active" if index.zero? %>">
        <div class="col-4 col-md-6 mx-auto"> 
          <% if user.avatar.attached? %>
            <%= image_tag(user.avatar, class: "img-fluid mx-auto d-block", style: "max-width: 70%;", alt: "#{user.full_name.titleize}'s avatar") %>
          <% else %>
            <%= image_tag("default-avatar.jpg", class: "d-block w-100", alt: "Default avatar") %>
          <% end %>
          <div class="carousel-caption d-block p-1">
            <div class="card w-100 mb-3">
             <div class="card-body p-2">
                <h5 class="card-title"><%= user.full_name.titleize %></h5>
                <p class="card-text"><%= user.bio %></p>
                <%= link_to "View profile", user_path(user.username), class: "btn btn-primary" %>

                <div class="d-flex justify-content-center">
                  <%= form_with url: like_match_by_username_path(username: user.username), method: :put, remote: true, class: "d-inline" do |form| %>
                    <%= form.submit "Like", class: "btn btn-success" %>
                    <% end %>

                    <%= form_with url: reject_match_by_username_path(username: user.username), method: :put, class: "d-inline" do |form| %>
                      <%= form.submit "Reject", class: "btn btn-danger" %>

                    <% end %>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% if @users.size > 1 %>
      <button class="carousel-control-prev" type="button" data-bs-target="#usersCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#usersCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  <% end %>
</div>

app/views/users/messages.html.erb
<%#This should probably be in the messages folder ; isn't it redundant with the messages/index file? %>

<div class="container">
  <div class="list-group">
    <% @messages.each do |message| %>
      <% message_user = message.sender == current_user ? message.receiver : message.sender %>
      <% match = message.match %>
      <a href="<%= match_messages_path(match) %>" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
        <div class="min-width-0">
          <%= image_tag(message_user.avatar.attached? ? message_user.avatar : 'default-avatar.jpg', size: "72x72", class: "rounded-circle flex-shrink-0", alt: "#{message_user.full_name.titleize}'s avatar") %>
        </div>
        <div class="d-flex gap-2 w-100 justify-content-between">
          <div>
            <h6 class="mb-0">
              <%= message.sender == current_user ? "#{message_user.username}" : "#{message_user.username}" %>
            </h6>
            <p class="mb-0 opacity-75">
              <%= message.body %>
            </p>
          </div>
          <small class="opacity-50 text-nowrap">
            <%= message.created_at.strftime("%b %d, %Y %H:%M") %>
          </small>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card mb-3">
        <div class="card-body text-center">
          <h1 class="card-title">
            <%= @user.full_name.titleize %>, <%= @user.age %>
          </h1>
          <% if policy(@user).edit? %>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>

      <% all_images = [] %>
      <% all_images << @user.avatar if @user.avatar.attached? %>
      <% @user.additional_files.each { |file| all_images << file if file.attached? } %>
      <% @user.additional_files_2.each { |file| all_images << file if file.attached? } %>
      <% @user.additional_files_3.each { |file| all_images << file if file.attached? } %>

      <% if all_images.any? %>
        <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
          <div class="carousel-indicators">
            <% all_images.each_with_index do |image, index| %>
              <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="<%= index %>"
                class="<%= 'active' if index == 0 %>" aria-current="<%= 'true' if index == 0 %>"
                aria-label="Slide <%= index + 1 %>">
              </button>
            <% end %>
          </div>

          <div class="carousel-inner">
            <% all_images.each_with_index do |image, index| %>
              <div class="carousel-item <%= 'active' if index == 0 %>" data-bs-interval="10000">
                <%= image_tag(image, class: "img-fluid mx-auto d-block", size: "300", alt: "Image #{index + 1}") %>
              </div>
            <% end %>
          </div>

          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      <% else %>

        <div class="text-center">
          <p>No images available.</p>
        </div>
      <% end %>

      <% if @user.bio.present? %>
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title"><strong>About me</strong></h5>
            <p class="card-text"><%= @user.bio %></p>
          </div>
        </div>
      <% end %>

      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><strong>My basics</strong></h5>
          <ul class="list-group list-group-flush">
            <% if @user.user_gym.present? %>
              <li class="list-group-item"><strong>The gym I go to:</strong> <span class="text-muted"><%= @user.gym_name %></span></li>
            <% end %>
            <% if @user.gender.present? %>
              <li class="list-group-item"><strong>My gender:</strong> <span class="text-muted"><%= @user.gender %></span></li>
            <% end %>
            <% if @user.time_of_day.present? %>
              <li class="list-group-item"><strong>I go to the gym at these times:</strong> <span class="text-muted"><%= @user.time_of_day %></span></li>
            <% end %>
            <% if @user.user_gym_frequency.present? %>
              <li class="list-group-item"><strong>How often do I go to the gym:</strong> <span class="text-muted"><%= @user.user_gym_frequency %></span></li>
            <% end %>
            <% if @user.skill_level.present? %>
              <li class="list-group-item"><strong>My skill level:</strong> <span class="text-muted"><%= @user.skill_level %></span></li>
            <% end %>
            <% if @user.type_of_workouts.present? %>
              <li class="list-group-item"><strong>Type of workouts I typically do:</strong> <span class="text-muted"><%= @user.workouts %></span></li>
            <% end %>
            <% if @user.ideal_match_gender.present? %>
              <li class="list-group-item"><strong>I'm looking to workout with:</strong> <span class="text-muted"><%= @user.ideal_match_gender.join(', ') %></span></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>