config/routes.rb
Rails.application.routes.draw do
  # you can add a conditional to only show this route to admins
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  root "pages#home"
  get "home" => "pages#home"
  devise_for :users

  resources :matches do
    resources :messages
  end



  put "/matches/:username/like", to: "matches#like", as: "like_match_by_username"

  put "/matches/:username/reject", to: "matches#reject", as: "reject_match_by_username"

   get "users/:username/messages", to: "users#messages", as: :user_messages

   get "/:username", to: "users#show", as: :user

  resources :users do
    collection do
      get "discover", to: "users#index", as: :discover_users
    end
  end

end

app/views/shared/_cdn_assets.html.erb
<!-- Connect Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">

<!-- Connect Bootstrap JavaScript and its dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>

<!-- Connect Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"></script>

app/views/shared/_flash.html.erb
<div class="alert alert-<%= css_class %> alert-dismissible fade show" role="alert">
  <%= message %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/shared/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="matchAcceptedModal" tabindex="-1" aria-labelledby="matchAcceptedModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="matchAcceptedModalLabel">Match Accepted</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Your match has been accepted!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color: #EF8354;">
  <div class="container">
    <%= link_to "Discover", discover_users_users_path, class: "navbar-brand text-white" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to matches_path, class: "nav-link text-white" do %>
              <i class="fas fa-users fa-fw"></i> Matches
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to user_messages_path(current_user.username), class: "nav-link text-white" do %>
              <i class="fas fa-envelope fa-fw"></i> Messages
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to user_path(current_user.username), class: "nav-link text-white" do %>
            <i class="fas fa-home fa-fw"></i> Your profile
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <div class="dropdown-menu bg-orange" aria-labelledby="navbarDropdown">
            <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item text-white" %>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item text-white" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link text-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>